# Generated by Django 4.2.6 on 2023-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_number',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
