# Generated by Django 4.2.6 on 2023-11-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
    ]
