# Generated by Django 4.2.6 on 2023-11-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('time_start', models.CharField(max_length=50)),
                ('time_end', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('appointment_with', models.CharField(blank=True, max_length=50)),
                ('update_time', models.DateField(auto_now=True)),
                ('frist_time', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='DefaultCategory', max_length=50)),
                ('type', models.CharField(default='DefaultType', max_length=50)),
                ('is_approved', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'On-Hold'), (3, 'Reject')], default=0)),
                ('reason', models.CharField(default='DefaultReason', max_length=50)),
                ('student_number', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(default='DefaultValue', max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
