# Generated by Django 4.2.6 on 2023-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
